# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170402_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
