# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_time',
        ),
    ]
